version: "3"

services:
  user:
    container_name: user
    image: goulkan/users:1.0
    ports:
      - 8001:8001
    networks:
      - node_network
  takens:
    container_name: takens
    image: goulkan/takens:1.0
    ports:
      - 8003:8003
    networks:
      - node_network
  projects:
    container_name: project
    image: goulkan/project:1.0
    ports:
    - 8002:8002
    networks:
      - node_network

networks: 
  node_network:
    name: node_network
