
name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CD
       - name: Deploy using ssh
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.PRIVATE_KEY }}
           port: 22
           script: |
             cd ~/home/auction/
             git pull origin master
             git status
             cd ~/home/auction/projects
             npm install 
             npm start 
             cd ~/home/auction/takens
             npm install 
             npm start 
             cd ~/home/auction/users
             npm install 
             npm start 
